// Week 1 session content extracted verbatim from FM1_v7_Facilitator_Manual_Book1.docx
// Source: LG_Hampshire_Pilot_v1.2 (2026-04-25) — DO NOT EDIT
// Regenerated 2026-05-01 from authoritative v7 source

export type DocParagraph = {
  style: 'Heading 1' | 'Heading 2' | 'Heading 3' | 'List Paragraph' | 'Normal';
  text: string;
};

export const WEEK1_CONTENT: DocParagraph[] = [
  { style: 'Normal', text: 'WEEK 1' },
  { style: 'Normal', text: 'WELCOME AND ORIENTATION' },
  { style: 'Normal', text: 'Introductory Session — Modified Rhythm' },
  { style: 'Normal', text: 'WHERE YOU ARE IN THE ARC' },
  { style: 'Normal', text: 'This is the first session of a fifty-two-week journey — but it is also the first session of a thirteen-week quarter. That distinction matters, and you will explain it today.' },
  { style: 'Normal', text: 'Book 1 — In The Quiet — covers the Foundation Quarter: Understanding and Acknowledging. Weeks 1–4 name grief and establish safety. Weeks 5–9 explore its dimensions. Weeks 10–13 begin the first integration work. Today you are laying the ground that everything else stands on.' },
  { style: 'Normal', text: 'Your job today is not to teach. It is not to cover content. It is to make this room safe enough, warm enough, and clear enough that people come back next week. If they leave feeling welcomed, understood, and clear about what to expect — you have succeeded.' },
  { style: 'Normal', text: 'FACILITATOR: This session uses a modified rhythm. Week 1 is an orientation, not a full content session. You are building the container. The deep work begins in Week 2. The thesis that governs everything you do in this room — today and for the next fifty-two weeks — is this: hope in despair is love seeking for love itself. You do not say those words to participants. You hold them. They will feel it in how you receive what they bring.' },
  { style: 'Normal', text: 'SESSION AT A GLANCE	90–100 min' },
  { style: 'Normal', text: 'Opening & Grounding	10 min	[IN SESSION]' },
  { style: 'Normal', text: 'Welcome & The Heart of Live and Grieve	20–25 min	[IN SESSION]' },
  { style: 'Normal', text: 'The Research — What Grief Actually Does	10–15 min	[IN SESSION]' },
  { style: 'Normal', text: 'Group Agreements	10 min	[IN SESSION]' },
  { style: 'Normal', text: 'Introductions & First Share	15 min	[IN SESSION]' },
  { style: 'Normal', text: 'Your Workbook — A Page-by-Page Walkthrough	10–15 min	[IN SESSION]' },
  { style: 'Normal', text: 'Between-Session Work & What Comes Next	5–10 min	[BETWEEN SESSIONS]' },
  { style: 'Normal', text: 'Closing Affirmation & Check-Out	5–10 min	[IN SESSION]' },
  { style: 'Normal', text: 'BEFORE THE SESSION — FACILITATOR PREPARATION' },
  { style: 'Normal', text: 'Room Checklist' },
  { style: 'Normal', text: 'FACILITATOR: Complete this before any participant arrives.' },
  { style: 'Normal', text: '□  Chairs arranged in a circle or semicircle. No tables between you and participants. You sit in the circle, not outside it. Same height as everyone else.' },
  { style: 'Normal', text: '□  A workbook placed on every chair. Participants find it waiting — they do not have to ask for it.' },
  { style: 'Normal', text: '□  Tissues available in at least two locations within the circle. Visible but not centered. You are prepared, not expecting.' },
  { style: 'Normal', text: '□  Water available.' },
  { style: 'Normal', text: '□  The five Group Agreements written on a whiteboard, flip chart, or poster — ready to be revealed, not already visible. You will introduce them together.' },
  { style: 'Normal', text: '□  Door visible to everyone from their seat. No one should feel trapped.' },
  { style: 'Normal', text: '□  Temperature comfortable. Check before people arrive.' },
  { style: 'Normal', text: '□  Crisis resource card at your seat: 988, Crisis Text Line (741741), SAMHSA (1-800-662-4357), NAMI (1-800-950-6264), 911.' },
  { style: 'Normal', text: '□  Your Facilitator Reflection Log — physical copy — at your seat.' },
  { style: 'Normal', text: '□  You have read the full WB1 Week 1 content. You know what participants will find when they open their workbook at home.' },
  { style: 'Normal', text: 'Inner Preparation' },
  { style: 'Normal', text: 'FACILITATOR REFLECTION:' },
  { style: 'Normal', text: '1.  What is your own emotional state right now? Name it specifically. Not “fine.” Not “ready.”' },
  { style: 'Normal', text: '2.  Have you read the Opening Reflection aloud — not silently — at least once? The words land differently spoken.' },
  { style: 'Normal', text: '3.  What are you afraid of? First sessions carry fear for facilitators too. Name it. It loses power when you look at it.' },
  { style: 'Normal', text: '4.  What is your intention for this session? Not what you will cover. What you will hold.' },
  { style: 'Normal', text: 'FACILITATOR: If a participant arrives in visible crisis BEFORE the session — shaking, hyperventilating, unable to speak — do not start the session. Go to them. Sit with them. Offer water. Ask: “Are you safe right now?” If they are not, call 988 together. If they are, ask: “Would you like to stay, or would you like me to walk you to your car?” Either answer is correct. The group can wait. Safety comes first.' },
  { style: 'Normal', text: 'OPENING & GROUNDING' },
  { style: 'Normal', text: '10 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'FACILITATOR: Read this slowly. Let the pauses be real, not performed. Breathe with them. Your calm is their first experience of safety. You are not performing stillness. You are being still.' },
  { style: 'Normal', text: '[WB1 VERBATIM — Opening Reflection]' },
  { style: 'Normal', text: 'SAY: “Welcome. Thank you for being here. Before we begin, I want to say something that matters: being in this room took courage. Whatever brought you here — whatever you are carrying — the fact that you showed up today says something about who you are and what you believe is possible. We are going to start the way we will start every session for the next year. With a moment of stillness. Find a comfortable position. If it feels right, close your eyes. If not, let your gaze rest somewhere soft — the floor, your hands, the space in front of you. Place one hand on your heart. Feel the weight of your own hand. Feel the rhythm underneath. Take three deep breaths. Not forced. Just slow, and deliberate, and yours.”' },
  { style: 'Normal', text: 'FACILITATOR: Pause. Breathe with them. Count silently — at least five full seconds between each breath.' },
  { style: 'Normal', text: '[WB1 VERBATIM — Opening Reflection, cont.]' },
  { style: 'Normal', text: 'SAY: “As you sit here at the beginning of this journey, acknowledge that you have taken an important step. There is no roadmap for grief that works for everyone. But there are companions and guides along the way. This workbook is one such companion. This group is another. Your courage in beginning this process is already a profound act of both honoring your loss and honoring your life. Breathe deeply once more. And when you are ready, open your eyes and continue.”' },
  { style: 'Normal', text: 'FACILITATOR: Allow 30–60 seconds of silence after finishing. Do not speak first. Let the room settle.' },
  { style: 'Normal', text: 'SAY: “That opening — the hand on the heart, the three breaths, the moment of stillness — will open every session we have together. Same beginning, every week. You will come to rely on it. The consistency is itself a kind of care.”' },
  { style: 'Normal', text: 'WATCH FOR' },
  { style: 'Normal', text: '•  The person who cannot close their eyes. Possible trauma history. The instruction says “if it feels right” — honor that. Do not comment.' },
  { style: 'Normal', text: '•  Crying before you finish. Let it happen. Do not stop reading. Your steady voice holds them.' },
  { style: 'Normal', text: '•  Late arrival. Welcome with a nod. Do not restart.' },
  { style: 'Normal', text: 'WELCOME & THE HEART OF LIVE AND GRIEVE' },
  { style: 'Normal', text: '20–25 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'FACILITATOR: This is the most important section of Session 1. You are not delivering information. You are connecting every person in this room to the reason this program exists. Speak from this — slowly, honestly. If your voice carries emotion, let it. This is grief work. Emotion belongs here. The three convictions that run through every session of every week of all 52 weeks are woven into what follows: grief and living are not opposites; the bond continues; every person’s grief is legitimate. You do not name them as “convictions.” You speak them as truth.' },
  { style: 'Normal', text: 'What This Program Is' },
  { style: 'Normal', text: 'SAY: “My name is [your name], and I am your facilitator for this program. Live and Grieve is a grief education program. Not therapy. Not counseling. Not a place where someone tells you how to feel or when to stop feeling it. It is a place where your grief is welcome for as long as it needs to be here. This program was built by two people who lost people they loved — and who could not find what they needed. So they built it. They did not come to grief research through a classroom. They came to research through grief — through their own, and through watching it move through the people they loved. By the time they found the research literature, they had already lived most of what it described. The Dual Process Model did not teach them that grief moves back and forth. It gave them the word for something they had already been doing without knowing what to call it. Continuing Bonds Theory did not teach them that love outlasts loss. They already knew that. The research came later, and it mattered — it gave structure to intuition and language to experience. But the experience came first. It always does. They built it because what they needed did not exist. And they believed no one should have to search the way they searched. They believe that grief and living are not opposites — that you can carry your loss and still engage with life, and that both are happening in you right now, wherever you are, whether anyone has named it or not. And they built it on the integrated architecture of five research frameworks and the philosophical influence of grief companion Alan Wolfelt — the life’s work of researchers who spent decades studying what grief actually does to human beings, joined to the companioning stance that shaped how we hold this room. Live and Grieve is the first peer grief education program built on this integrated architecture. That matters, because grief is not one thing. It is many things happening at once. A program that only addresses one dimension of grief leaves you holding the rest alone. This program does not do that. It holds all of it. For a full year.”' },
  { style: 'Normal', text: 'What This Room Is' },
  { style: 'Normal', text: 'SAY: “This room is a container. That word matters. A container holds things safely. It does not fix them. It does not rush them. It holds them. Every week, you will come into this room and find the same structure waiting for you. We will open the same way — hand on heart, three breaths. We will close the same way — an affirmation read together, a one-word check-out. In between, you will engage with your grief and with your life, because this program believes those are not opposites. I want to pause on that word — AND. The name of this program is Live AND Grieve. Not live after you grieve. Not grieve until you can live again. Both. At the same time. That small word carries the entire philosophy of what we do here. You are already doing it. You are grieving AND you are still here. You are carrying loss AND you are still breathing. This program gives that reality structure and company. You do not have to choose between grief and life. You never did.”' },
  { style: 'Normal', text: 'How the Program Is Structured' },
  { style: 'Normal', text: 'SAY: “Live and Grieve is a fifty-two-week program, but it is built in four quarters — four books of thirteen weeks each. Each quarter has its own theme, its own workbook, and its own focus. Book 1 — In The Quiet — is about understanding and acknowledging. This is where we are now. We name the grief. We learn what it is. We begin to sit with it honestly. Book 2 — Through The Weight — is about exploring and processing. We go deeper. Book 3 — Toward the Light — is about integrating and adapting. We begin to find how grief and life fit together. Book 4 — With the Memory — is about growing and connecting. We carry the love forward. Here is what I want you to know: these four quarters can be done in any order. If someone joins us in Book 2, they are not behind. If someone starts with Book 4 and then comes back for Book 1, that is valid. Each quarter is complete on its own. Each workbook stands alone. There is no wrong door into this program.”' },
  { style: 'Normal', text: 'FACILITATOR: Pause here. Let this land. For many participants, the idea that they are not “behind” is the first relief they have felt in months.' },
  { style: 'Normal', text: 'If You Miss a Session' },
  { style: 'Normal', text: 'SAY: “Life happens. Grief happens. There will be weeks when you cannot be here. I want you to hear this clearly: if you miss a session, you have not fallen behind. You have not failed. You have not lost your place. When you come back, we will be glad to see you. Your chair will be here. Your workbook will pick up wherever you left off. The group will welcome you back without question. This program is not a class where you miss a lecture and cannot catch up. It is a circle. The circle does not close when you step away. It holds your space until you return.”' },
  { style: 'Normal', text: 'FACILITATOR: This is particularly important for participants in acute grief. Some will miss sessions because getting out of bed is too much. Normalizing absence removes the shame that keeps people from returning.' },
  { style: 'Normal', text: 'What I Am and What I Am Not' },
  { style: 'Normal', text: 'SAY: “I am your facilitator. I am here to walk beside you through this. Not ahead of you. Not above you. Beside you. I am not a therapist. I am not here to diagnose you, treat you, or tell you what your grief should look like. I am here to hold this space, to keep it safe, to make sure every person in this circle is seen and heard. I am trained in this program and in trauma-informed facilitation. That means I understand how grief moves through a person, and I know how to hold a room where that movement is happening. But I am not the expert on your grief. You are. You have been living it. You know more about your grief than any framework or any facilitator ever will. What I offer is structure, consistency, and presence. What you bring is everything else. If at any point your grief feels unmanageable — if you are in crisis, if you are having thoughts of harming yourself — I will help you connect with professional support. That is not a failure of this program. That is this program working exactly as it should. Your workbook has crisis resources in the back — 988 is available 24/7 by call or text. We know our boundaries, and we honor them.”' },
  { style: 'Normal', text: 'THE RESEARCH' },
  { style: 'Normal', text: 'WHAT GRIEF ACTUALLY DOES — 10–15 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'FACILITATOR: Do not skip this section. Participants need to understand the research foundation BEFORE they go home to write “My Grief Story.” The framework gives their experience a name. For many, this will be the first time anyone has told them that what they are going through is not pathology — it is the process working correctly. Deliver this in your own words. Accessible language only.' },
  { style: 'Normal', text: 'Grief Is Bigger Than You Think' },
  { style: 'Normal', text: 'SAY: “Before we go further, I want to talk about what grief actually is — because most of us grew up with a version of it that is incomplete. We were taught that grief is about death. It is — but it is also about the end of a relationship, the loss of health, the loss of a role, the loss of who you thought you would be. Anything that was important and is no longer present. If you have lost something that mattered, you are grieving. That is not dramatic. That is accurate. And grief does not just live in your emotions. It shows up in your body — fatigue, tension, chest tightness, that feeling of being ‘off’ that you cannot explain. It shows up in your thinking — fog, forgetfulness, the sense that the world has become unfamiliar. It shows up in your behavior — withdrawal, restlessness, searching. And it shows up in your spirit — questioning what you believe, searching for meaning. All of that is grief. Not just the crying. All of it. And all of it belongs in this room.”' },
  { style: 'Normal', text: 'What the Research Says' },
  { style: 'Normal', text: 'SAY: “This program is built on five research frameworks and the philosophical influence of grief companion Alan Wolfelt — bodies of research and stance that have studied and held grief for decades. I am not going to lecture you on them. But I want you to hear what they found, because it matters for what you are going through right now. The first is called the Dual Process Model. Researchers named Margaret Stroebe and Henk Schut studied how people actually grieve — not how textbooks say they should grieve, but how they actually do it. And what they found is this: grief does not move in stages. It does not go in a straight line. It moves back and forth. Some days you are in the grief — fully, completely. The wave hits and you are inside it. Other days you are functioning. You go to work. You cook dinner. You laugh at something and then feel guilty for laughing. Both of those days are grief working correctly. You oscillate between facing the loss and engaging with life. Back and forth. That movement is not failure. It is not backsliding. It is the process. And every session in this program carries both sides — a Grief Processing activity that faces the loss, and a Living Forward activity that turns toward life. Not because we are rushing you. Because both are always present. The second thing the research tells us comes from a man named William Worden. He said grief is not something that happens to you. It is something you do. It has tasks — accepting the reality of the loss, processing the pain, adjusting to a world that has changed, and finding a way to carry the love forward. Tasks. Not stages. Things you actively do. That is what this workbook is for — it gives you the space to do that work. The third thing — and for many people this is the one that matters most — comes from researchers named Klass, Silverman, and Nickman. For decades, the grief field told people that healthy grieving meant letting go. Severing the bond. Moving on. These researchers challenged that. They found that the bond does not break. It changes form. The love does not end. It releases into something different. You do not have to let go of the person you lost. You never have to let go. You carry them with you. This program is built on that belief. The fourth is about meaning — the work of Robert Neimeyer. He found that meaning can emerge from loss without requiring that the loss was good or necessary. And sometimes meaning does not come at all, and carrying that absence is its own kind of work. The fifth is self-compassion — Kristin Neff’s research. Learning to hold yourself with enough gentleness to look honestly at what you are carrying. For many people in this program, that practice becomes the floor everything else stands on. And alongside these five research frameworks is the companioning stance — the work of Alan Wolfelt. Wolfelt is not a research framework but a philosophical influence on this program: he shaped the most important decision we made in building it: how to position me. I am not here as an expert with answers. I am here to hold the room while you do your own work — a steady light beside the weight you came in with. That distinction changes everything.”' },
  { style: 'Normal', text: 'FACILITATOR: Let this sit. Do not rush into the next section. If someone is visibly moved, acknowledge it: “What you are feeling right now is real. That is what this program is for.”' },
  { style: 'Normal', text: 'SAY: “Those five research frameworks and the Wolfelt companioning influence are the foundation of everything in your workbook, everything in this room, and everything we will do together for the next year. You do not need to memorize them. You will live them.”' },
  { style: 'Normal', text: 'GROUP AGREEMENTS' },
  { style: 'Normal', text: '10 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'FACILITATOR: These are not rules you read to them. They are agreements the group makes together. Introduce each one. Explain why it matters. Reveal the written agreements on the board or flip chart as you go. These agreements will be referenced throughout all 52 weeks — in Week 5 (sharing boundaries), Week 8 (no-fixing during trigger work), Week 10 (right to pass during difficult emotions), and Week 13 (reflecting on what they made possible).' },
  { style: 'Normal', text: 'SAY: “Before we go any further, we need to build the foundation of this room together. These are not rules. They are agreements — promises we make to each other about how we will be in this space.”' },
  { style: 'Normal', text: 'Agreement 1: Confidentiality' },
  { style: 'Normal', text: 'SAY: “What is shared in this room stays in this room. You may talk about your own experience outside this group. You may not share anyone else’s story, words, or identity. This is non-negotiable. Without it, nothing else works.”' },
  { style: 'Normal', text: 'Agreement 2: The Right to Pass' },
  { style: 'Normal', text: 'SAY: “You always have the right to pass. On any question. On any activity. On any share. Passing is not a failure. It is self-care. No one will ask you why. No one will pressure you to change your mind.”' },
  { style: 'Normal', text: 'Agreement 3: No Fixing' },
  { style: 'Normal', text: 'SAY: “When someone shares their grief in this room, our job is to witness it — not to fix it. No advice. No ‘have you tried…’ No ‘at least…’ No silver linings. Grief does not need to be solved. It needs to be held. We hold it by listening.”' },
  { style: 'Normal', text: 'Agreement 4: No Comparing' },
  { style: 'Normal', text: 'SAY: “Every loss in this room is real. We do not rank grief. We do not say ‘at least you had them for twenty years’ or ‘at least it wasn’t sudden.’ There is no hierarchy of pain here. Your grief is yours. It is enough to qualify you for this room.”' },
  { style: 'Normal', text: 'Agreement 5: Presence Over Performance' },
  { style: 'Normal', text: 'SAY: “You do not have to perform recovery in this room. You do not have to show progress. You do not have to be brave, or strong, or okay. You just have to be here. However you show up today — that is enough.”' },
  { style: 'Normal', text: 'SAY: “Can we agree to these together?”' },
  { style: 'Normal', text: 'FACILITATOR: Pause for verbal or visible affirmation from each participant. If someone hesitates: “Take whatever time you need with these. They will be here every week.” Write all five visibly. They stay posted for every session through all 13 weeks.' },
  { style: 'Normal', text: 'INTRODUCTIONS & FIRST SHARE' },
  { style: 'Normal', text: '15 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'FACILITATOR: This is NOT the group discussion from a standard session. You are asking for names and one sentence. Not grief stories. The deep sharing begins in Week 2. The bar is deliberately low.' },
  { style: 'Normal', text: 'SAY: “I would like to go around the circle and hear from each of you. Just your name and one sentence — whatever feels right. It could be what brought you here. It could be one word about how you are feeling. It could be the name of the person you lost, if you are ready to say it. There is no wrong answer. I will go first.”' },
  { style: 'Normal', text: 'FACILITATOR: Share your name and one honest sentence. Model vulnerability briefly — under 30 seconds. Then go around. After each person, pause. Make eye contact. Say: “Thank you, [name].” Nothing more. Do not reflect, interpret, or connect their words to anyone else’s.' },
  { style: 'Normal', text: 'SAY: “Thank you — every one of you. What just happened is not small. You showed up. You said your name. You let yourself be seen. That is how this begins.”' },
  { style: 'Normal', text: 'WATCH FOR' },
  { style: 'Normal', text: '•  Someone in acute grief who cannot speak. “Your presence is your introduction. Thank you for being here.”' },
  { style: 'Normal', text: '•  Someone who over-shares. Gently: “I want to honor everything you are carrying. We will have so much time for your story. For right now, can you give me one sentence?”' },
  { style: 'Normal', text: '•  Someone who uses humor to deflect. Receive it warmly. Do not call it out.' },
  { style: 'Normal', text: 'YOUR WORKBOOK' },
  { style: 'Normal', text: 'A PAGE-BY-PAGE WALKTHROUGH — 10–15 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'FACILITATOR: Have everyone pick up their workbook. This is a physical walkthrough. They touch the pages, see the colors, understand the structure. Familiarity reduces anxiety. Do not rush this. If workbooks didn’t arrive or a participant forgot theirs, you can speak the prompts aloud and direct them to write in a notebook — the content in this session guide is sufficient to run without the workbook present.' },
  { style: 'Normal', text: 'SAY: “I want you to pick up your workbook. This book is your companion for the next thirteen weeks. It is yours — write in it, mark it up, fold the corners. It is not precious. It is practical. It goes where you go. Let’s walk through it together.”' },
  { style: 'Normal', text: 'The Weekly Structure' },
  { style: 'Normal', text: 'SAY: “Open to Week 1. Every week follows the same structure. Let me show you what you will find. At the top: an Opening Reflection. That is what we just did together — the hand on the heart, the breathing. It is printed here so you can return to it any time, even at home, even alone. Below that: the Educational Component. This is the week’s theme explained in plain, honest language. It is not a textbook. It is the research translated into something you can feel, not just read. Then you will see a green callout box — the Key Concept. This is the one idea from the research that anchors the week. One thing to carry.”' },
  { style: 'Normal', text: 'The Three Activity Colors' },
  { style: 'Normal', text: 'SAY: “Now look at the activities. You will notice three different colors. These colors are not decoration. They mean something. Pink is for Grief Processing. [Hold up the page or point.] These activities face the loss directly. They ask you to look at your grief — to name it, to write about it, to sit with it. The pink says: this is tender ground. You are allowed to be here. Blue is for Living Forward. [Point to the blue section.] These activities turn toward life — not away from grief, but alongside it. Setting intentions. Building connections. Finding what is still possible. The blue says: there is still a world out here, and you are still in it. Lavender is for Self-Care. [Point to the lavender section.] These activities are about caring for yourself through the process. Body, mind, spirit. The lavender says: you deserve the same tenderness you would give someone you love. Every week. Pink, blue, lavender. Grief, life, self. You will start to recognize the rhythm just by the colors.”' },
  { style: 'Normal', text: 'The Write-In Areas' },
  { style: 'Normal', text: 'SAY: “Inside each activity you will see write-in areas — boxes with lines. Some have prompts. Some are open. This is where you do the work. You write. Nobody else reads it unless you choose to share. This workbook is private. It belongs to you.”' },
  { style: 'Normal', text: 'Journal Prompts, Affirmation, Gratitude, Tracker' },
  { style: 'Normal', text: 'SAY: “After the three activities, you will find four more elements. They are the same every week. Journal Prompts — questions for deeper reflection. Do one, do all of them, or skip them entirely. They are invitations, not assignments. A Weekly Affirmation — a grounding statement to carry with you. I will read it aloud at the close of every session, and it is here for you to return to during the week whenever you need it. A Gratitude Practice — one line per day, seven days. Even amid grief, noticing one small thing you are grateful for can provide balance. This is not toxic positivity. It is honest noticing. One thing. That is all. And a Weekly Progress Tracker — four dimensions, a simple 1-to-5 scale. Grief intensity, connection to others, self-care, hope. You circle where you are. No right answers. This is not a test. It is a mirror. Over thirteen weeks, you will see patterns you cannot see in the moment. And at the end of each week, you will find a closing statement. A few lines that hold what the week was about. You can read it as a bookend — a way of putting the week’s work down before the next one begins.”' },
  { style: 'Normal', text: 'Resources' },
  { style: 'Normal', text: 'SAY: “Turn to the back of your workbook. You will find a Resources section with crisis support numbers — 988, Crisis Text Line, SAMHSA. Grief organizations. Professional referral guidance. These are here for the moments when this program is not enough, and that is okay. You also have the full References — the five research frameworks and the Wolfelt companioning philosophical influence and the work behind them. An About section that tells the story of the program and the four-book series. And the program’s website — tripillarstudio.com — where you will find additional resources, information about the program, and a community of people walking this same path. This workbook has everything you need. It is complete.”' },
  { style: 'Normal', text: 'BETWEEN-SESSION WORK & WHAT COMES NEXT' },
  { style: 'Normal', text: '5–10 minutes' },
  { style: 'Normal', text: '[BETWEEN SESSIONS]' },
  { style: 'Normal', text: 'SAY: “Before we close, I want to walk you through what to do this week between now and our next session. Three things. None of them are difficult. All of them matter. First: read the Educational Component for Week 1. It is in your workbook — one page. It covers what we just talked about: what grief is, how it moves back and forth, why that movement is not failure. Reading it at home will deepen what you heard today. Second: begin the Grief Processing Activity — ‘My Grief Story.’ This is the pink section. Turn to it now.”' },
  { style: 'Normal', text: 'FACILITATOR: Wait until everyone has found the page.' },
  { style: 'Normal', text: 'SAY: “This activity asks you to begin writing about your loss. You will see prompts: Who you lost. When it happened. The circumstances surrounding the loss. And then deeper questions — what the first days were like, how your grief has changed, where you are now. Write as much or as little as feels right. If all you can write is a name and a date, that is enough. If the words pour out, let them. There is no minimum and no maximum. This is your story. And if you do not finish it — that is fine. If you open the page and close it again — that is fine. If you show up next week with a blank workbook — you are still welcome in this room. Showing up is the work. Everything else builds from there. Do not let an incomplete page keep you from coming back. A word about pacing: do not try to do everything in one sitting. Spread the writing across the week. Give your grief room to breathe between the pages. Write a little Monday. Sit with it Tuesday. Come back Wednesday. There is no rush. The workbook will wait for you. Third: look at the Self-Care Practice — ‘Comfort Corner.’ This is the lavender section. It asks you to create a small space in your home with items that comfort your senses — something to see, hear, smell, touch, taste. Build it this week if you can. When grief arrives — and it will — your nervous system reaches for something physical before your mind catches up — having something ready is how you meet yourself there. And one more thing — tonight, before you go to bed, open to the Gratitude Practice for this week and write one thing. Just one. It does not have to be big. ‘The sun came through the window.’ ‘Someone held the door.’ ‘I made it to this room.’ One line. That is enough to start.”' },
  { style: 'Normal', text: 'FACILITATOR: Do not introduce the Living Forward Activity (“Setting Intentions”) this week. That will be introduced in the Week 2 session after participants have had the experience of writing their grief story. Loss-oriented work comes before restoration-oriented work in the opening sequence. This is deliberate.' },
  { style: 'Normal', text: 'What to Expect This Week' },
  { style: 'Normal', text: 'SAY: “I want to prepare you for what might happen between now and next week. You opened a door today. You sat in a room and let yourself be seen. You are going to go home and begin writing about your loss — maybe for the first time. That may stir things up. Grief may arrive at unexpected moments. You may feel heavier before you feel lighter. You may cry in the grocery store. You may feel nothing and worry that means something is wrong. You may feel relief and then feel guilty about the relief. All of that is normal. All of that is the grief moving, which means it is no longer stuck. If it gets hard, go to your Comfort Corner. If it gets harder than that, turn to the Resources section in the back of your workbook — 988 is there, available 24/7. If you need to reach me between sessions, [provide your preferred contact — email, phone, or program-specific channel]. You are not alone between meetings.”' },
  { style: 'Normal', text: 'What Comes Next Week' },
  { style: 'Normal', text: 'SAY: “Next week is Week 2 — The Nature of Grief. We will go deeper into what grief looks like and how it shows up in the body, the mind, and the spirit. As we walk through next week’s workbook pages together, what you wrote this week — your grief story, what you noticed, what came up — will naturally be part of the conversation. Not because I ask you to present it. Because the content connects. What you experience at home lives in the room the following week. The workbook and the group feed each other. You will feel it. So when you come back, bring your workbook. Bring whatever you wrote — or did not write. And bring yourself — however you are that day.”' },
  { style: 'Normal', text: 'CLOSING AFFIRMATION & CHECK-OUT' },
  { style: 'Normal', text: '5–10 minutes' },
  { style: 'Normal', text: '[IN SESSION]' },
  { style: 'Normal', text: 'Weekly Affirmation' },
  { style: 'Normal', text: 'FACILITATOR: Read this aloud. Slowly. This is the last thing they hear before they walk back into the world. It matters.' },
  { style: 'Normal', text: 'SAY: “I want to close with this week’s affirmation. You will find it in your workbook. I am going to read it aloud. Follow along silently, or read it with me — whatever feels right.”' },
  { style: 'Normal', text: '[WB1 VERBATIM — Affirmation]' },
  { style: 'Normal', text: 'SAY: “I honor my grief as an expression of love. I give myself permission to feel all of my emotions. Each day, I will take one small step in caring for myself while carrying my loved one in my heart.”' },
  { style: 'Normal', text: 'FACILITATOR: Pause at least five seconds. Let the words settle.' },
  { style: 'Normal', text: 'The Closing Statement' },
  { style: 'Normal', text: 'SAY: “And at the bottom of your Week 1 pages, you will find a closing statement. Let me read it to you now:”' },
  { style: 'Normal', text: '[WB1 VERBATIM — Closing Statement]' },
  { style: 'Normal', text: 'SAY: “You wrote something down. You set a direction. You built something your body can reach for when language runs out. Week 1 is not preparation for the work. Week 1 is the work. You have already begun.”' },
  { style: 'Normal', text: 'FACILITATOR: Pause. Let this land. This closing statement is printed in the workbook and read aloud in the session. Participants will find one at the end of every week. This is the bookend to the Opening Reflection — how the week closes. Establish this pattern now.' },
  { style: 'Normal', text: 'One-Word Check-Out' },
  { style: 'Normal', text: 'SAY: “We are going to close the way we will close every session — with a one-word check-out. One word that describes where you are right now. Not where you think you should be. Where you actually are. There is no wrong word. ‘Heavy’ is a word. ‘Tired’ is a word. ‘Hopeful’ is a word. ‘Here’ is a word. I will go first.”' },
  { style: 'Normal', text: 'FACILITATOR: Say your word. Go around the circle. Thank each person by name. After the last person:' },
  { style: 'Normal', text: 'SAY: “Thank you — every one of you — for what you brought into this room today. Take your workbook home. Read through Week 1. Begin writing your grief story when you are ready — gently, across the week. Build your comfort corner. Write one thing in your gratitude practice tonight. At the end of the week, open the tracker and circle where you are — just noticing, no judging. And if you want to explore more about this program, what it offers, and the community behind it — tripillarstudio.com. Everything is there. Grief is not linear. There will be ups and downs between now and next week. Be gentle with yourself. And know this: next week, this room will be here. This circle will be here. I will be here. You are not carrying this alone anymore. I will see you next week.”' },
  { style: 'Normal', text: 'AFTER THE SESSION — FACILITATOR DEBRIEF' },
  { style: 'Normal', text: 'FACILITATOR: Do not leave the building immediately. Sit with what happened. Complete your Facilitator Reflection Log — the physical document at your seat — before the details soften.' },
  { style: 'Normal', text: 'FACILITATOR REFLECTION:' },
  { style: 'Normal', text: '1.  What was the tone of the room? Not what you hoped for. What it actually was.' },
  { style: 'Normal', text: '2.  Who do you want to follow up with? Someone who seemed flooded? Someone who did not speak? Someone who left early?' },
  { style: 'Normal', text: '3.  Did every participant affirm the group agreements? If someone hesitated, note it. That is information for Week 2.' },
  { style: 'Normal', text: '4.  What did you handle well today? Name one moment.' },
  { style: 'Normal', text: '5.  What would you do differently? Not what you did wrong. What you would adjust.' },
  { style: 'Normal', text: '6.  What are you carrying from this session? Facilitators absorb grief. Name what you are holding and decide what to do with it before next week.' },
  { style: 'Normal', text: 'FACILITATOR: Week 2 moves through the workbook content on grief reactions. As you walk through the educational component together, what participants wrote in “My Grief Story” will surface naturally — the grief they named at home is the grief the content is now describing. Prepare for the possibility that some participants will arrive having written pages. Others will arrive having written nothing. Both are valid. Your job is to receive whatever they bring as it comes. The container you built today is what makes that possible. The circle has begun.' },
  { style: 'Normal', text: 'Hope in despair' },
  { style: 'Normal', text: 'is love seeking' },
  { style: 'Normal', text: 'for love itself.' },
];

export const IWG_CONTENT: DocParagraph[] = [
  { style: 'Normal', text: 'LIVE AND GRIEVE™' },
  { style: 'Normal', text: 'The Facilitator’s Inner Work' },
  { style: 'Normal', text: 'A Guide to Becoming the Facilitator This Work Requires' },
  { style: 'Normal', text: 'For all certified and certifying facilitators' },
  { style: 'Normal', text: 'Wayne & Jamie Simms  ·  Tri-Pillars™ LLC' },
  { style: 'Normal', text: '© 2025 Tri-Pillars™ LLC. All Rights Reserved.' },
  { style: 'Heading 1', text: 'A Note Before You Begin' },
  { style: 'Normal', text: 'The Facilitator Certification Training teaches you what to do. This guide asks something harder: it asks you to look at who you are when you do it.' },
  { style: 'Normal', text: 'Most facilitation failures are not failures of knowledge. Facilitators who struggle in the room usually know the research. They know the session structure. They know the crisis protocol. What they did not know — or had not examined — was themselves.' },
  { style: 'Normal', text: 'They did not know that their own unprocessed grief about their father would surface when a participant talked about theirs. They did not know that their discomfort with silence would fill every pause with words that weren’t needed. They did not know that their need to fix things — to make people feel better — would prevent them from sitting in the one place participants most need them to sit: right here, in this, with me.' },
  { style: 'Normal', text: 'This guide is organized around five areas of inner work. None of them can be completed once. All of them are ongoing. You will return to these questions every year you facilitate, and what you find will change as you do.' },
  { style: 'Normal', text: 'Read slowly. Write honestly. If something lands hard, stay with it.' },
  { style: 'Normal', text: 'CHAPTER 1' },
  { style: 'Normal', text: 'Your Grief History' },
  { style: 'Normal', text: 'What you carry into every room you enter' },
  { style: 'Normal', text: 'Nobody facilitates grief from a neutral place. You have lost people. You have experienced grief that was witnessed and grief that was not. You have had losses that were honored and losses that were dismissed. All of that is in the room with you, whether or not you named it during training.' },
  { style: 'Normal', text: 'This is not a liability. Lived experience with loss is one of your most important assets as a facilitator. It is the source of your credibility, your empathy, and your ability to say “I know” and mean it. But unexamined lived experience is something different. Unexamined, it leads you into the room wearing your own grief like a lens you don’t know you’re wearing.' },
  { style: 'Normal', text: 'The question is not whether your grief enters the room. It does. The question is whether you know it’s there.' },
  { style: 'Heading 2', text: 'The Inventory' },
  { style: 'Normal', text: 'Before you facilitate your first group, complete this inventory honestly. Return to it at every annual renewal.' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'List the significant losses in your life. Not just deaths — include losses of relationship, identity, health, safety, or meaning. For each one, write: How old were you? Who supported you? How did you grieve — or not grieve — at the time?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Which of these losses feel fully integrated — present but not raw? Which ones are still active in some way?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'If you were sitting in your own group as a participant, which week’s topic would be hardest for you to sit with? What would that activate?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Have you done your own grief work — through therapy, a grief group, spiritual practice, or another process? If not, what is getting in the way?' },
  { style: 'Heading 2', text: 'What This Means in Practice' },
  { style: 'Normal', text: 'Knowing your grief history does not mean it won’t surface in the room. It means you will recognize it when it does. That recognition is the difference between a moment you can manage and a moment that manages you.' },
  { style: 'Normal', text: 'When a participant’s story lands close to something in your own history, you may notice: a tightening in your chest, an urge to speak, a wave of your own emotion, a desire to end the moment sooner than it needs to end. These are signals. They are not instructions.' },
  { style: 'Normal', text: 'When you notice a signal, you have a choice. You can pause, breathe, stay in the room, and let the participant’s experience belong to them. Or you can let your history pull you somewhere that isn’t yours to go.' },
  { style: 'Normal', text: 'PRACTICE:  The Recognition Practice' },
  { style: 'List Paragraph', text: 'After each session, sit with this question for 5 minutes: Was there a moment where I felt something that belonged to me rather than to the group?' },
  { style: 'List Paragraph', text: 'Write it down in your Facilitator Reflection Log without judgment' },
  { style: 'List Paragraph', text: 'Note what the trigger was, what you noticed in your body, and what you did' },
  { style: 'List Paragraph', text: 'Over time, patterns will emerge — these patterns are your growth edge' },
  { style: 'Normal', text: 'CHAPTER 2' },
  { style: 'Normal', text: 'The Presence You Bring' },
  { style: 'Normal', text: 'Regulated facilitators create regulated rooms' },
  { style: 'Normal', text: 'Your nervous system is one of your primary facilitation tools. Before you say a word, before you read the opening reflection, before anyone shares, your nervous system is broadcasting to every person in the room. A regulated facilitator creates a regulated room. An activated facilitator — anxious, rushed, unprocessed, distracted — creates an activated room.' },
  { style: 'Normal', text: 'This is not metaphor. It is neuroscience. Human nervous systems co-regulate. The facilitator is the most influential nervous system in the room by virtue of position and role. If you walk in unsettled, the group will feel it before you speak.' },
  { style: 'Normal', text: 'You are the environment. Before you say anything, you are already communicating.' },
  { style: 'Heading 2', text: 'What Regulation Looks Like' },
  { style: 'Normal', text: 'Regulation does not mean emotional flatness. It does not mean performing calm while feeling chaotic. It means your nervous system is in a window of tolerance — present, available, grounded — from which you can respond rather than react.' },
  { style: 'Normal', text: 'Regulated facilitation looks like: slowing down when the room speeds up. Allowing silence without filling it. Receiving difficult material without flinching or overcorrecting. Being moved without being swept away. Staying curious when the room gets uncomfortable.' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Think of a time when you were facilitating — or in any high-stakes interpersonal moment — when you were genuinely regulated. What did that feel like in your body? What made it possible?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Think of a time when you were activated in the room. What happened? What did you do? What do you wish you had done?' },
  { style: 'Heading 2', text: 'Your Arrival Practice' },
  { style: 'Normal', text: 'The 15 minutes before a session begins are not administrative time. They are the most important 15 minutes of your preparation. The room should be set. Every logistical task should be complete. Those 15 minutes are yours to arrive.' },
  { style: 'Normal', text: 'An arrival practice is a brief, consistent ritual that signals to your nervous system: I am here. I am ready. This moment is not about me.' },
  { style: 'Normal', text: 'PRACTICE:  Designing Your Arrival Practice' },
  { style: 'List Paragraph', text: 'Choose a duration: 5, 10, or 15 minutes before participants arrive' },
  { style: 'List Paragraph', text: 'Choose a body-based anchor: slow breath, brief walk, hands on a surface, standing outside the door' },
  { style: 'List Paragraph', text: 'Set a clear intention: name what you are there for. Not what you will do — who you will be' },
  { style: 'List Paragraph', text: 'Let go of what came before: a difficult commute, a hard day, your own needs. Not permanently — just for now' },
  { style: 'List Paragraph', text: 'Enter the room as if you mean to be there. Because you do.' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Write your arrival practice. Be specific — not "I will breathe" but exactly what, for how long, with what intention.' },
  { style: 'Heading 2', text: 'After the Session' },
  { style: 'Normal', text: 'Sessions do not end when participants leave. They end when you have completed your own transition out. This is especially important after difficult sessions — disclosures, activations, conflict, or your own emotional responses to the material.' },
  { style: 'Normal', text: 'Without a close, the material follows you home. It shows up in your sleep, your relationships, your next session. A closing practice does not eliminate this — it creates a container so that what belongs to the session stays in the session.' },
  { style: 'Normal', text: 'PRACTICE:  A Simple Session Close' },
  { style: 'List Paragraph', text: 'After participants leave, sit in the empty room for 3–5 minutes' },
  { style: 'List Paragraph', text: 'Name aloud (or in writing) what was present: "Tonight someone shared ___. The room held ___. I felt ___."' },
  { style: 'List Paragraph', text: 'Breathe and release: "I receive what was mine. I release what was not."' },
  { style: 'List Paragraph', text: 'Complete your Facilitator Reflection Log' },
  { style: 'List Paragraph', text: 'Do one physical transition: change clothes, take a walk, wash your hands — something that marks the boundary' },
  { style: 'Normal', text: 'CHAPTER 3' },
  { style: 'Normal', text: 'The Companions You Need' },
  { style: 'Normal', text: 'This work requires a support structure' },
  { style: 'Normal', text: 'One of the most common mistakes new facilitators make is attempting to do this work alone. They prepare alone, they facilitate alone, and they process alone. This is unsustainable, and it is a risk to the people they serve.' },
  { style: 'Normal', text: 'Grief facilitation is demanding at a level that is not always visible from the outside. Sessions that look calm may be carrying enormous weight. A participant’s disclosure that took thirty seconds can stay with a facilitator for days. The accumulation of holding other people’s grief — over weeks, over years — changes something. The question is not whether it will affect you. The question is whether you have the support structures to metabolize what you absorb.' },
  { style: 'Normal', text: 'You cannot pour from an empty vessel. This is not a cliché. It is a clinical reality.' },
  { style: 'Heading 2', text: 'Three Support Structures Every Facilitator Needs' },
  { style: 'Normal', text: 'These are not optional. They are the scaffolding that makes sustainable facilitation possible.' },
  { style: 'Normal', text: 'A Peer Consultant' },
  { style: 'Normal', text: 'Someone who facilitates grief support or holds a similar role and can receive your experience without judgment. Not a therapist. Not a supervisor. A peer — someone who knows what the room feels like. Meet with them regularly, not only when things are hard. The goal is ongoing relationship, not crisis debriefing.' },
  { style: 'Normal', text: 'A Personal Support Structure' },
  { style: 'Normal', text: 'Therapy, spiritual direction, a grief group of your own, a trusted relationship where you can be the one who is not okay. This work requires that you have places where the role is reversed — where someone else holds you. If you do not have this, build it before your first group.' },
  { style: 'Normal', text: 'A Supervision Relationship with Tri-Pillars™' },
  { style: 'Normal', text: 'The Facilitator Reflection Log creates a written record of your experience over time. Tri-Pillars™ is available for consultation on complex situations. Use this resource. It exists specifically so you do not have to navigate difficult situations alone.' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Who are your current peer consultants? If you do not have one, name one person you could approach. What would you need to say to begin that relationship?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'What is your current personal support structure? Where do you go when you are not okay? Is it enough for this work?' },
  { style: 'Heading 2', text: 'Secondary Traumatic Stress — Know the Signs' },
  { style: 'Normal', text: 'Secondary traumatic stress (STS) is the occupational residue of sustained exposure to others’ trauma and grief. It is not a sign of weakness. It is a sign that you are human and that the work is real.' },
  { style: 'Normal', text: 'STS in facilitators typically looks like: intrusive thoughts about a participant’s story; emotional numbness or avoidance after sessions; hypervigilance or heightened anxiety in and around facilitation; difficulty separating participant experiences from your own; loss of meaning or compassion fatigue; disrupted sleep related to session material.' },
  { style: 'Normal', text: 'If you recognize these signs in yourself, the response is not to push through. The response is to activate your support structures, reduce your caseload if possible, and seek consultation from Tri-Pillars™ LLC.' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Have you experienced any of these signs before — in this work or in other caregiving roles? What helped? What made it worse?' },
  { style: 'Normal', text: 'CHAPTER 4' },
  { style: 'Normal', text: 'The Silence and the Space' },
  { style: 'Normal', text: 'What you do not say is as powerful as what you do' },
  { style: 'Normal', text: 'New facilitators almost universally struggle with silence. The discomfort is understandable — silence in a room full of grieving people can feel like abandonment, like failure, like an absence of care. The impulse to fill it with something — a reflection, a reframe, a kind word — is natural and well-intentioned.' },
  { style: 'Normal', text: 'It is also, very often, exactly the wrong thing to do.' },
  { style: 'Normal', text: 'Silence is where grief lives. It is what happens between the words, in the space after someone shares something they have never said aloud. Filling that space immediately sends a message: this is uncomfortable and we need to move. It teaches the group that stillness is something to escape rather than something to inhabit.' },
  { style: 'Normal', text: 'The most powerful thing you can do after someone shares is nothing. Receive it. Let it land.' },
  { style: 'Heading 2', text: 'Learning to Hold Silence' },
  { style: 'Normal', text: 'Holding silence is a skill. It requires a regulated nervous system — which is why Chapter 2 comes before this one. If you are activated, silence feels unbearable. If you are regulated, silence feels like what it is: the natural breath of a room that is present.' },
  { style: 'Normal', text: 'Practical guidance:' },
  { style: 'List Paragraph', text: 'Count to five in your head after someone finishes speaking before you consider responding. Most of the time, the group will respond before you need to.' },
  { style: 'List Paragraph', text: 'Lower your gaze slightly when someone is sharing. It communicates reception, not vacancy.' },
  { style: 'List Paragraph', text: 'Let your own breath be audible. A slow exhale from the facilitator regulates the room.' },
  { style: 'List Paragraph', text: 'If silence lasts longer than feels comfortable, name it rather than fill it: "Let’s stay with that for a moment."' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'On a scale of 1–10, how comfortable are you with silence in emotionally charged settings? What drives your impulse to fill it? What would it mean to trust the silence?' },
  { style: 'Heading 2', text: 'The Words You Choose' },
  { style: 'Normal', text: 'When you do speak, every word is a choice. The language of grief facilitation is not casual language. It is precise, intentional, and grounded in what the research tells us about how people move through loss.' },
  { style: 'Normal', text: 'Language That Closes' },
  { style: 'Normal', text: 'Language That Opens' },
  { style: 'Normal', text: '"At least you had so many good years together."' },
  { style: 'Normal', text: '"What has it been like to carry this?"' },
  { style: 'Normal', text: '"I know exactly how you feel."' },
  { style: 'Normal', text: '"Tell me more about that."' },
  { style: 'Normal', text: '"You’re so strong."' },
  { style: 'Normal', text: '"That took a lot to say."' },
  { style: 'Normal', text: '"Everything happens for a reason."' },
  { style: 'Normal', text: '"That doesn’t have to make sense right now."' },
  { style: 'Normal', text: '"Have you tried...?"' },
  { style: 'Normal', text: '"What feels most true for you right now?"' },
  { style: 'Normal', text: '"You should be further along by now."' },
  { style: 'Normal', text: '"There is no timeline here."' },
  { style: 'Normal', text: '"It was God’s plan."' },
  { style: 'Normal', text: '"I’m here with you in this."' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Which of the "closing" phrases do you find yourself drawn to, even though you know better? What does that impulse protect in you?' },
  { style: 'Heading 2', text: 'The 80/20 Discipline' },
  { style: 'Normal', text: 'You should be speaking no more than 20% of session time. This is harder than it sounds, especially in the early weeks when participants are finding their footing and the silence feels uncertain.' },
  { style: 'Normal', text: 'The 80/20 rule is not a performance metric. It is a structural reminder of what your role is. You are not the content. You are the container. The content is what participants bring. Your job is to create and maintain the conditions under which that content can emerge safely.' },
  { style: 'Normal', text: 'If you are talking more than 20% of the time, something has shifted. You are performing rather than facilitating. You are managing your own discomfort rather than holding the group’s. Notice it. Return to the role.' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'Think of a facilitation moment — real or imagined — where you filled space that did not need to be filled. What were you protecting yourself from? What did the group miss because of it?' },
  { style: 'Normal', text: 'CHAPTER 5' },
  { style: 'Normal', text: 'The Facilitator You Are Becoming' },
  { style: 'Normal', text: 'This is a practice, not a destination' },
  { style: 'Normal', text: 'There is no arrival in this work. There is no moment when you become the finished facilitator, when the inner work is done, when grief stops landing in unexpected places. The most experienced grief facilitators in the world still have sessions that shake them. They still encounter moments that reveal new layers of their own history. The difference is not that they have outgrown the difficulty. The difference is that they have developed the capacity to be with it.' },
  { style: 'Normal', text: 'That capacity is what this guide is about. And it is built slowly, through practice, through honest reflection, and through the kind of sustained attention to yourself that most of us were never taught to offer.' },
  { style: 'Normal', text: 'You bring yourself into every room. The invitation is to know who that is.' },
  { style: 'Heading 2', text: 'The Annual Review' },
  { style: 'Normal', text: 'At every certification renewal, return to this guide. Read it as if for the first time. The chapters that felt resolved will open new questions. The ones that felt hard will land differently. This is not because the guide changes. It is because you do.' },
  { style: 'Normal', text: 'Complete the following at every annual renewal:' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'How has your relationship to grief — your own and others’ — changed since your last renewal? What has this work taught you about loss?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'What was the most difficult facilitation moment of the past year? What did you do? What would you do differently now?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'What has this work asked of you that you did not expect? Are you willing to keep giving it?' },
  { style: 'Normal', text: 'REFLECTION' },
  { style: 'Normal', text: 'What does your support structure look like right now? Is it adequate for the work you are doing? What needs to change?' },
  { style: 'Heading 2', text: 'A Final Word' },
  { style: 'Normal', text: 'The people who enter your groups are carrying some of the heaviest things a human being can carry. They will trust you with those things. They will sit in a circle with strangers because you have created a space that felt safe enough.' },
  { style: 'Normal', text: 'That is not a small thing. It will never be a small thing, no matter how many groups you facilitate.' },
  { style: 'Normal', text: 'Do this work with your whole self. Prepare your mind with the research. Prepare your practice with the curriculum. And prepare your heart with honest attention to the person you are when you walk through that door.' },
  { style: 'Normal', text: 'The rest will follow.' },
  { style: 'Normal', text: 'Live and Grieve™  ·  The Facilitator’s Inner Work' },
  { style: 'Normal', text: '© 2025 Tri-Pillars™ LLC. All Rights Reserved.' },
  { style: 'Normal', text: 'wayne@tripillarstudio.com  ·  jamie@tripillarstudio.com  ·  tripillarstudio.com' },
  { style: 'Normal', text: 'Crisis Resources: 988 Suicide & Crisis Lifeline (call or text 988, 24/7)  ·  Crisis Text Line: Text HOME to 741741  ·  Veterans Crisis Line: Call 988, press 1' },
];

export const PAG_CONTENT: DocParagraph[] = [
  { style: 'Normal', text: 'LIVE AND GRIEVE™' },
  { style: 'Normal', text: 'Participant Appropriateness Guide' },
  { style: 'Normal', text: 'A Screening Framework for Facilitators, Referring Professionals, and Partner Organizations' },
  { style: 'Normal', text: 'This guide answers one question: is this person ready for Live and Grieve™ right now? It does not determine whether someone deserves support — it determines whether this particular format is the right support at this particular time.' },
  { style: 'Normal', text: 'Live and Grieve™ is a structured peer support group. It is not therapy, crisis intervention, or a clinical treatment program. Its power comes from its structure, its consistency, and the relational environment of a group. That power depends on participants who are able to engage with all three.' },
  { style: 'Normal', text: 'Who This Program Is Designed For' },
  { style: 'Normal', text: 'Live and Grieve™ is designed for adults who are:' },
  { style: 'Normal', text: '•  Experiencing grief following significant loss — most commonly the death of a close family member or long-term partner' },
  { style: 'Normal', text: '•  Able to participate in a group setting without clinical instability — they can sit with the emotional content of a session without becoming dysregulated in a way that disrupts the group or requires clinical intervention' },
  { style: 'Normal', text: '•  Not in acute psychiatric crisis at the time of enrollment' },
  { style: 'Normal', text: '•  Willing to commit to weekly attendance for a 13-week quarter' },
  { style: 'Normal', text: '•  Seeking a structured peer support experience alongside or instead of individual support' },
  { style: 'Normal', text: 'The program also serves individuals experiencing significant non-death losses: the end of a long-term relationship, loss of a career or vocation, loss of identity through serious illness or disability, or cumulative grief across multiple losses. These participants are appropriate when the other criteria above are met.' },
  { style: 'Normal', text: 'Appropriateness Indicators' },
  { style: 'Normal', text: 'The following indicators suggest a person is appropriate for the program. These are not requirements — they are the profile of a participant who is likely to benefit and to contribute to the group.' },
  { style: 'Normal', text: 'Stable Enough to Engage' },
  { style: 'Normal', text: 'The person is not in a state of acute crisis. They may be in significant pain — that is expected and appropriate. But they are able to arrive at a session, sit in a circle, hear others share, and participate in a structured format without becoming so overwhelmed that they cannot continue.' },
  { style: 'Normal', text: 'Grief that is acute, raw, and close to the surface is entirely appropriate for this program. Grief that is currently producing psychiatric instability — active suicidal ideation, acute trauma responses, significant dissociation, or psychosis — belongs in clinical support first.' },
  { style: 'Normal', text: 'Able to Hold Confidentiality' },
  { style: 'Normal', text: 'The person understands and can commit to the group confidentiality agreement. They will not share what others say in the group outside the group.' },
  { style: 'Normal', text: 'Not Seeking Therapy in a Group Format' },
  { style: 'Normal', text: 'The person understands that this is a peer support group, not a therapy group. The facilitator is not their therapist. The group is not a substitute for individual clinical support that is clinically indicated.' },
  { style: 'Normal', text: 'Willing to Attend Consistently' },
  { style: 'Normal', text: 'The person is able to commit to weekly attendance for 13 weeks. Life will interrupt — occasional absences are expected. But the person\'s baseline intention is consistent presence. A participant who plans to attend only four or five sessions should not join a cohort: their partial participation undermines the group\'s relational continuity.' },
  { style: 'Normal', text: 'Situations That Warrant Careful Consideration' },
  { style: 'Normal', text: 'The following situations do not automatically exclude someone from the program, but they warrant a conversation — with the referring professional, the facilitator, and ideally with the person being referred — before enrollment.' },
  { style: 'Normal', text: 'Current Individual Therapy for Complicated Grief' },
  { style: 'Normal', text: 'A person who is currently in individual therapy specifically for complicated grief may benefit from the group as a complement to individual work — but the therapist and facilitator should be aware of each other\'s involvement. The group should not be asked to hold what individual therapy is already addressing.' },
  { style: 'Normal', text: 'Very Recent Loss — Within the Past Four to Six Weeks' },
  { style: 'Normal', text: 'A person in the earliest weeks of acute grief may find the group format overwhelming before some initial processing has occurred. This is a judgment call, not a hard rule. Some people in early acute grief are well-served by beginning the group immediately. Others need a few weeks before they can hold the relational complexity of a group. Consider whether the person has any support in place in the very early period.' },
  { style: 'Normal', text: 'Significant Trauma Alongside Grief' },
  { style: 'Normal', text: 'When a death occurred through violence, suicide, or sudden traumatic accident, the grief is often complicated by trauma — PTSD-range responses that require trauma-informed clinical treatment alongside or before group support. These participants may be appropriate for the group, but their trauma history should be known to the facilitator, and individual trauma support should be in place or actively sought.' },
  { style: 'Normal', text: 'Participants with complex PTSD or active trauma symptomatology that significantly impairs daily functioning should begin with individual trauma-informed support before enrolling in the group.' },
  { style: 'Normal', text: 'Active Substance Use as a Coping Mechanism' },
  { style: 'Normal', text: 'A person who is actively using alcohol or substances to manage grief-related distress may find that the group\'s emotional opening accelerates the need for clinical support they do not yet have in place. These participants are not excluded — but the facilitator and referring professional should be aware, and the person should ideally have individual support in place before beginning the group.' },
  { style: 'Normal', text: 'Cognitive or Communication Differences' },
  { style: 'Normal', text: 'The program\'s written workbook and group discussion format is designed to be accommodated in most situations. Participants with cognitive or communication differences are welcome — facilitators can adapt the format as needed. Contact Tri-Pillars™ LLC to discuss options.' },
  { style: 'Normal', text: 'Who the Program Is Not Designed For' },
  { style: 'Normal', text: 'The following situations indicate that Live and Grieve™ is not the appropriate support at this time. Referral to a more appropriate resource is the right response.' },
  { style: 'Normal', text: 'Acute Psychiatric Crisis' },
  { style: 'Normal', text: 'Active suicidal ideation with plan or intent. Active psychosis. Acute manic episode. Any mental health presentation that requires crisis intervention or inpatient-level care. These individuals need clinical stabilization before any group support program.' },
  { style: 'Normal', text: 'Current Active Addiction Without Clinical Support' },
  { style: 'Normal', text: 'A person whose primary presenting issue is substance dependence, where grief is a contributing factor but not the primary clinical concern, belongs in addiction treatment — not a grief support group. The group cannot serve as the primary clinical container for addiction.' },
  { style: 'Normal', text: 'Seeking Individual Therapy in a Group Format' },
  { style: 'Normal', text: 'A person who consistently expects the group to function as individual therapy — who monopolizes group time, who seeks private consultation from the facilitator between sessions, or who resists the peer-support structure — is not appropriately placed. This is often identifiable in pre-enrollment conversations.' },
  { style: 'Normal', text: 'Active Behavioral Disruption Risk' },
  { style: 'Normal', text: 'A person whose behavior is likely to significantly harm the group environment — through persistent disruption, inability to maintain confidentiality, or aggressive behavior — is not appropriate for a group format at this time. This is a rare situation and should be assessed carefully rather than assumed.' },
  { style: 'Normal', text: 'The Pre-Enrollment Conversation' },
  { style: 'Normal', text: 'Every prospective participant should have a brief conversation with the facilitator before their first session. This is not a clinical screening interview — it is an orientation conversation. Its purpose is:' },
  { style: 'Normal', text: '•  To ensure the person understands what the program is and is not' },
  { style: 'Normal', text: '•  To confirm their understanding of and commitment to the group agreements' },
  { style: 'Normal', text: '•  To allow the facilitator to make a basic appropriateness judgment' },
  { style: 'Normal', text: '•  To answer the participant\'s questions before they are in the room with the group' },
  { style: 'Normal', text: 'The pre-enrollment conversation is also an opportunity to identify any significant circumstances the facilitator should be aware of — recent trauma, concurrent clinical support, specific loss circumstances — so they can be prepared to hold what arrives.' },
  { style: 'Normal', text: 'The pre-enrollment conversation is not a barrier to participation. It is a care practice. Most people who inquire about the program are appropriate for it. The conversation exists to ensure that the program is positioned to serve the person well — and that the person is not placed in a format that could do harm by being wrong for where they are.' },
  { style: 'Normal', text: 'When to Consult Tri-Pillars™' },
  { style: 'Normal', text: 'Contact Tri-Pillars™ LLC (wayne@tripillarstudio.com) when:' },
  { style: 'Normal', text: '•  You are uncertain whether a specific person is appropriate and want consultation before deciding' },
  { style: 'Normal', text: '•  A person has enrolled and you are concerned mid-cohort that the format is not right for them' },
  { style: 'Normal', text: '•  You are considering asking a participant to pause or discontinue participation' },
  { style: 'Normal', text: '•  A referral source is sending participants who do not fit the appropriateness criteria and you need support in managing the relationship' },
  { style: 'Normal', text: 'Live and Grieve™  ·  Tri-Pillars™ LLC  ·  Wayne & Jamie Simms, Founders' },
  { style: 'Normal', text: 'tripillarstudio.com  ·  wayne@tripillarstudio.com  ·  © 2025 Tri-Pillars™ LLC. All Rights Reserved.' },
  { style: 'Normal', text: 'If a participant presents in crisis during or after screening: Suicide & Crisis Lifeline — call or text 988. Veterans Crisis Line — 988, press 1. Do not proceed with enrollment until the crisis is resolved. Complete a Critical Incident Report and contact wayne@tripillarstudio.com within 24 hours.' },
];

export const COC_CONTENT: DocParagraph[] = [
  { style: 'Normal', text: 'LIVE AND GRIEVE™' },
  { style: 'Normal', text: 'Facilitator Code of Conduct' },
  { style: 'Normal', text: 'All Certification Tracks · All Authorized Contexts' },
  { style: 'Normal', text: 'This Code of Conduct governs all individuals holding a current Live and Grieve™ Facilitator Certification issued by Tri-Pillars™ LLC.' },
  { style: 'Normal', text: 'Signing this document is a condition of certification and must be renewed annually.' },
  { style: 'Normal', text: '© 2025 Tri-Pillars™ LLC. All Rights Reserved.' },
  { style: 'Normal', text: 'wayne@tripillarstudio.com  ·  tripillarstudio.com' },
  { style: 'Heading 1', text: 'Preamble' },
  { style: 'Normal', text: 'The Live and Grieve™ program was built because grief deserves to be held with care, dignity, and skill. Every person who enters a Live and Grieve™ group is carrying real loss. They are trusting that the facilitator in that room has prepared, knows their boundaries, and will protect the space.' },
  { style: 'Normal', text: 'This Code of Conduct exists to honor that trust. It is not a bureaucratic requirement. It is a commitment — to the people we serve, to each other as a community of facilitators, and to the integrity of this program.' },
  { style: 'Normal', text: 'Every Live and Grieve™ Facilitator, regardless of certification track, organizational context, or years of experience, is held to the same standard. This Code applies in every setting where the program is delivered, including in-person groups, virtual groups, and any context where a facilitator represents the Live and Grieve™ program publicly.' },
  { style: 'Heading 1', text: 'The Code' },
  { style: 'Normal', text: '01' },
  { style: 'Normal', text: 'Participant Wellbeing Comes First' },
  { style: 'Normal', text: 'The safety, dignity, and wellbeing of every participant is the primary obligation of every session. All other considerations are secondary.' },
  { style: 'List Paragraph', text: 'Never prioritize session completion over participant safety' },
  { style: 'List Paragraph', text: 'Recognize when a participant needs support beyond the scope of this program and act on it' },
  { style: 'List Paragraph', text: 'Never allow group dynamics, time pressure, or personal discomfort to prevent an appropriate safety response' },
  { style: 'List Paragraph', text: 'Maintain appropriate aftercare awareness — participants do not end at the session door' },
  { style: 'Normal', text: '02' },
  { style: 'Normal', text: 'Operate Within Scope of Practice' },
  { style: 'Normal', text: 'A Live and Grieve™ Facilitator provides structured grief support within a defined curriculum. This role does not extend to clinical assessment, diagnosis, therapy, or spiritual direction.' },
  { style: 'List Paragraph', text: 'Never diagnose, label, or clinically assess a participant’s mental health' },
  { style: 'List Paragraph', text: 'Never provide therapeutic interventions beyond the scope of the curriculum' },
  { style: 'List Paragraph', text: 'Never position yourself as a counselor, therapist, psychologist, or spiritual director unless you hold those credentials independently and are operating in a separate, clearly distinct capacity' },
  { style: 'List Paragraph', text: 'When a participant’s needs exceed the scope of the program, refer promptly and warmly' },
  { style: 'Normal', text: '03' },
  { style: 'Normal', text: 'Protect Confidentiality' },
  { style: 'Normal', text: 'What is shared in a Live and Grieve™ group stays in that group. Confidentiality is foundational to the psychological safety participants require to engage fully.' },
  { style: 'List Paragraph', text: 'Never share participant disclosures with anyone outside the group without explicit permission, except as required by mandatory reporting obligations' },
  { style: 'List Paragraph', text: 'Never discuss a participant’s experience with their family members, employers, referring organizations, or other facilitators without participant consent' },
  { style: 'List Paragraph', text: 'Inform participants of the confidentiality boundaries and the mandatory reporting exception in the first session, every time' },
  { style: 'List Paragraph', text: 'Protect participant records, attendance documentation, and any identifying information from unauthorized access' },
  { style: 'Normal', text: '04' },
  { style: 'Normal', text: 'Fulfill Mandatory Reporting Obligations' },
  { style: 'Normal', text: 'Confidentiality does not apply when there is credible reason to believe that a participant or a third party is at risk of serious harm. Facilitators are obligated to act.' },
  { style: 'List Paragraph', text: 'Know the mandatory reporting laws in your jurisdiction before your first session' },
  { style: 'List Paragraph', text: 'Report immediately when you have credible knowledge of abuse of a child, elder, or dependent adult' },
  { style: 'List Paragraph', text: 'Act without delay when a participant expresses suicidal ideation or intent to harm another person' },
  { style: 'List Paragraph', text: 'Document every crisis event using the Critical Incident Report (Appendix E) within 24 hours and notify Tri-Pillars™ LLC' },
  { style: 'Normal', text: '05' },
  { style: 'Normal', text: 'Maintain Appropriate Boundaries' },
  { style: 'Normal', text: 'The facilitator-participant relationship carries inherent power. Facilitators are responsible for maintaining boundaries that protect participants and the integrity of the group.' },
  { style: 'List Paragraph', text: 'Do not enter into romantic, sexual, financial, or dependent relationships with current participants' },
  { style: 'List Paragraph', text: 'Avoid dual relationships that could compromise your ability to hold a neutral, safe space' },
  { style: 'List Paragraph', text: 'Do not accept gifts of significant monetary value from participants' },
  { style: 'List Paragraph', text: 'If a boundary becomes unclear or complicated, seek supervision before proceeding' },
  { style: 'List Paragraph', text: 'Boundary violations involving current participants are grounds for immediate certification review' },
  { style: 'Normal', text: '06' },
  { style: 'Normal', text: 'Deliver the Program with Fidelity' },
  { style: 'Normal', text: 'Participants in every Live and Grieve™ group deserve to receive the program as designed. The curriculum has been developed with care, grounded in research, and tested in practice.' },
  { style: 'List Paragraph', text: 'Facilitate from the current authorized version of the Master Facilitator Manual' },
  { style: 'List Paragraph', text: 'Do not substitute, omit, or significantly alter curriculum content without written authorization from Tri-Pillars™' },
  { style: 'List Paragraph', text: 'Do not combine Live and Grieve™ curriculum with other grief programs without written authorization' },
  { style: 'List Paragraph', text: 'Do not represent modified or unofficial content as Live and Grieve™ programming' },
  { style: 'List Paragraph', text: 'Maintain documentation as required and submit records to Tri-Pillars™ upon request' },
  { style: 'Normal', text: '07' },
  { style: 'Normal', text: 'Represent the Program and Brand with Integrity' },
  { style: 'Normal', text: 'Every certified facilitator is a representative of Live and Grieve™ and Tri-Pillars™. Public conduct, marketing materials, and organizational communications must reflect this.' },
  { style: 'List Paragraph', text: 'Use authorized Tri-Pillars™ and Live and Grieve™ branding materials only — do not create unofficial logos, wordmarks, or program materials' },
  { style: 'List Paragraph', text: 'Do not make claims about program outcomes that exceed what the research supports' },
  { style: 'List Paragraph', text: 'Do not imply endorsement by Tri-Pillars™ for activities outside your certification scope' },
  { style: 'List Paragraph', text: 'Disclose your certification track and authorized context accurately in all professional representations' },
  { style: 'List Paragraph', text: 'Do not use the Live and Grieve™ name or brand to promote personal services, other programs, or commercial products without written authorization' },
  { style: 'Normal', text: '08' },
  { style: 'Normal', text: 'Practice Self-Care and Seek Support' },
  { style: 'Normal', text: 'Facilitating grief is demanding work. A facilitator who is burned out, unprocessed, or activated is a risk to participants. Self-care is not optional — it is a professional obligation.' },
  { style: 'List Paragraph', text: 'Maintain and follow the self-regulation plan developed during certification training' },
  { style: 'List Paragraph', text: 'Seek peer supervision or professional support when sessions are consistently difficult' },
  { style: 'List Paragraph', text: 'Do not facilitate when you are in acute personal crisis without appropriate supervision in place' },
  { style: 'List Paragraph', text: 'Recognize and respond to signs of secondary traumatic stress in yourself' },
  { style: 'List Paragraph', text: 'Maintain your own grief work through appropriate personal or professional channels' },
  { style: 'Normal', text: '09' },
  { style: 'Normal', text: 'Pursue Ongoing Competency' },
  { style: 'Normal', text: 'The field of grief support continues to evolve. A commitment to ongoing learning is part of the facilitator’s professional obligation.' },
  { style: 'List Paragraph', text: 'Complete annual certification renewal requirements by the renewal deadline' },
  { style: 'List Paragraph', text: 'Stay informed about updates to the Live and Grieve™ curriculum and apply them promptly' },
  { style: 'List Paragraph', text: 'Engage with available supervision, peer consultation, and continuing education opportunities' },
  { style: 'List Paragraph', text: 'Notify Tri-Pillars™ promptly if your professional credentials, employment status, or organizational context changes significantly' },
  { style: 'Normal', text: '10' },
  { style: 'Normal', text: 'Report Concerns and Cooperate with Review' },
  { style: 'Normal', text: 'Maintaining the integrity of the program requires that concerns about facilitator conduct — including your own — are reported and addressed.' },
  { style: 'List Paragraph', text: 'Report concerns about another facilitator’s conduct to Tri-Pillars™ in good faith and without delay' },
  { style: 'List Paragraph', text: 'Cooperate fully with any review, investigation, or inquiry initiated by Tri-Pillars™' },
  { style: 'List Paragraph', text: 'Do not retaliate against any person who reports a concern in good faith' },
  { style: 'List Paragraph', text: 'Acknowledge and report your own conduct violations rather than concealing them — transparency is considered in all reviews' },
  { style: 'Heading 1', text: 'Violations & Consequences' },
  { style: 'Normal', text: 'Violations of this Code are taken seriously. The appropriate response depends on the nature, severity, and context of the violation. Tri-Pillars™ retains sole authority to determine the appropriate response in all cases.' },
  { style: 'Normal', text: 'Category' },
  { style: 'Normal', text: 'Examples & Potential Response' },
  { style: 'Normal', text: 'Administrative Violation' },
  { style: 'Normal', text: 'Missed documentation deadline, late renewal, failure to submit required forms. Response: written notice, required remediation within 30 days.' },
  { style: 'Normal', text: 'Practice Violation' },
  { style: 'Normal', text: 'Curriculum modification without authorization, scope drift, failure to refer when required, unauthorized brand use. Response: formal review, required remediation or supervision, possible suspension.' },
  { style: 'Normal', text: 'Boundary Violation' },
  { style: 'Normal', text: 'Inappropriate relationship with a participant, dual relationship that compromises group safety, financial exploitation. Response: immediate suspension pending investigation, possible permanent revocation.' },
  { style: 'Normal', text: 'Safety Violation' },
  { style: 'Normal', text: 'Failure to fulfill mandatory reporting obligations, failure to act on a disclosed safety risk, concealment of a critical incident. Response: immediate revocation of certification, possible legal referral.' },
  { style: 'Normal', text: 'Integrity Violation' },
  { style: 'Normal', text: 'Misrepresentation of credentials, fraudulent documentation, use of the Live and Grieve™ name outside authorized scope for personal gain. Response: immediate revocation, public disclosure as appropriate.' },
  { style: 'Normal', text: 'Revocation of certification is permanent unless explicitly reinstated in writing by the Tri-Pillars™ founders. No facilitator whose certification has been revoked for a boundary, safety, or integrity violation is eligible for reinstatement.' },
  { style: 'Heading 1', text: 'Attestation & Signature' },
  { style: 'Normal', text: 'By signing below, I affirm that:' },
  { style: 'List Paragraph', text: 'I have read this Code of Conduct in its entirety and understand each principle and its implications for my practice' },
  { style: 'List Paragraph', text: 'I agree to be bound by this Code for the duration of my certification and in all contexts where I represent Live and Grieve™ or Tri-Pillars™' },
  { style: 'List Paragraph', text: 'I understand that violations of this Code may result in suspension or revocation of my certification' },
  { style: 'List Paragraph', text: 'I commit to seeking supervision, guidance, or clarification from Tri-Pillars™ LLC when I am uncertain about my obligations under this Code' },
  { style: 'List Paragraph', text: 'I will complete this attestation annually as a condition of certification renewal' },
  { style: 'Normal', text: 'Facilitator Information' },
  { style: 'Normal', text: 'Full Legal Name' },
  { style: 'Normal', text: 'Certification Track' },
  { style: 'Normal', text: 'Organization / Institutional Context' },
  { style: 'Normal', text: 'Certification ID Number' },
  { style: 'Normal', text: 'Facilitator Signature' },
  { style: 'Normal', text: 'Date Signed' },
  { style: 'Normal', text: 'For Tri-Pillars™ Use Only' },
  { style: 'Normal', text: 'Received by: ___________________________   Date received: _______________   Filed: □' },
  { style: 'Normal', text: 'Renewal year: ___________   Certification status confirmed: □ Active  □ Suspended  □ Pending review' },
  { style: 'Normal', text: 'Submit completed form to: wayne@tripillarstudio.com  ·  Retain a copy for your records' },
];
