// Week 1 session content extracted verbatim from LG_Master_Facilitator_Manual_Book1_FINAL.docx
// DO NOT EDIT — source of truth is the DOCX in facilitator-documents/02_FACILITATOR/
// Extracted 2026-03-30. Style values match DOCX paragraph styles exactly.

export type DocParagraph = {
  style: 'Heading 1' | 'Heading 2' | 'Heading 3' | 'List Paragraph' | 'Normal';
  text: string;
};

export const WEEK1_CONTENT: DocParagraph[] = [
  { style: 'Heading 1', text: 'Week 1: Introduction to the Dual Process of Grieving and Living' },
  { style: 'Heading 2', text: 'Theme: Introducing the dual process of grief' },
  { style: 'Normal', text: '\u25c9 SESSION AT-A-GLANCE  \u00b7  Week 1  \u00b7  75\u201385 min' },
  { style: 'Normal', text: '  Opening & Grounding \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 10 min' },
  { style: 'Normal', text: '  Educational Overview \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 10\u201315 min' },
  { style: 'Normal', text: '  Group Discussion & Sharing \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 20\u201325 min' },
  { style: 'Normal', text: '  Grief Processing Activity \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 15 min' },
  { style: 'Normal', text: '  Living Forward Activity \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 10 min' },
  { style: 'Normal', text: '  Self-Care Practice \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 5 min' },
  { style: 'Normal', text: '  Closing & Check-Out \u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7\u00b7 5 min' },
  { style: 'Normal', text: '\u25c8 BEFORE THE SESSION  \u00b7  Facilitator Preparation' },
  { style: 'Normal', text: '1.  What is your own emotional state entering this first session? Name it specifically before you walk in.' },
  { style: 'Normal', text: '2.  Have you read the Opening Reflection for Week 1 aloud \u2014 not silently \u2014 at least once? The words land differently spoken.' },
  { style: 'Normal', text: '3.  What does it mean to you to hold grief and living in the same breath? This is what you\u2019re asking participants to do for a year.' },
  { style: 'Normal', text: '\u25b8  First sessions carry disproportionate weight. The safety established here \u2014 or not \u2014 shapes every session that follows. Some participants will arrive within weeks of their loss. Prioritize presence over content.' },
  { style: 'Heading 2', text: 'Suggested Discussion Questions' },
  { style: 'List Paragraph', text: 'What brings you here today \u2014 what are you hoping this group might offer?' },
  { style: 'List Paragraph', text: 'When you think about grief, what words or images come to mind?' },
  { style: 'List Paragraph', text: 'What has surprised you most about your own grief experience?' },
  { style: 'Heading 2', text: 'Session Guide \u2014 Week 1' },
  { style: 'Normal', text: 'Total session time: 60\u201390 minutes. Timing is approximate \u2014 follow the group\u2019s emotional energy.' },
  { style: 'Heading 2', text: 'Opening & Grounding' },
  { style: 'Normal', text: '\u23f1 10 minutes' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Opening Reflection' },
  { style: 'Normal', text: 'Take a moment to settle into a comfortable position. Close your eyes if that feels right for you. Place one hand on your heart and take three deep breaths. As you sit here at the beginning of this journey, acknowledge that you have taken an important step toward healing. There is no roadmap for grief that works for everyone, but there are companions and guides along the way. This workbook is one such companion. Your courage in beginning this process is already a profound act of both honoring your loss and honoring your life. Breathe deeply once more, and when you\u2019re ready, open your eyes and continue.' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Opening Reflection for Week 1 before continuing.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitator Instructions' },
  { style: 'Normal', text: 'Read the Opening Reflection aloud, verbatim, slowly. Allow intentional pauses. When finished, allow 30\u201360 seconds of silence before speaking.' },
  { style: 'Normal', text: 'Facilitator Tip: Week 1: Introduce the ritual of the Opening Reflection \u2014 explain that it will open every session throughout the year. This consistency is itself a grief support.' },
  { style: 'Heading 2', text: 'Educational Overview' },
  { style: 'Normal', text: '\u23f1 10\u201315 minutes' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Educational Component' },
  { style: 'Normal', text: 'Educational Component: What is Grief and How Does It Affect Us?' },
  { style: 'Normal', text: 'Grief is our natural response to loss\u2014a complex blend of emotions, thoughts, physical sensations, and behaviors that emerge when someone or something important to us is no longer present in our lives. While we often associate grief with death, we can experience grief after many types of losses: the end of a relationship, loss of health, loss of a job or role, or even the loss of hopes and dreams.' },
  { style: 'Normal', text: 'Grief is not a single emotion but rather a constellation of experiences that may include:' },
  { style: 'Normal', text: 'Emotional responses: Sadness, anger, guilt, anxiety, relief, numbness, loneliness, yearning, and even moments of joy or peace.' },
  { style: 'Normal', text: 'Physical sensations: Fatigue, changes in appetite or sleep, tension, chest pain or tightness, sensitivity to noise or light, and a general sense of being \u201cunwell.\u201d' },
  { style: 'Normal', text: 'mental effects: Difficulty concentrating, forgetfulness, confusion, preoccupation with thoughts of the deceased, sensing their presence, or questioning your beliefs.' },
  { style: 'Normal', text: 'Behavioral changes: Crying, social withdrawal, restlessness, searching behaviors, avoiding or seeking reminders, changes in activity levels.' },
  { style: 'Normal', text: 'Spiritual dimensions: Questioning faith or beliefs, finding comfort in spiritual practices, searching for meaning, feeling connected to something larger than yourself.' },
  { style: 'Normal', text: 'It\u2019s important to understand that grief is not a linear process with clear stages that you move through in sequence. Rather, it\u2019s more like a winding path with unexpected turns, occasional backtracking, and gradual forward movement. The dual process model of grief suggests that we naturally oscillate between focusing on our loss (grief work) and focusing on restoration (adapting to life changes and looking forward). Both orientations are necessary and healthy parts of the grieving process.' },
  { style: 'Normal', text: 'Your grief is as unique as your relationship with the person you\u2019ve lost. There is no \u201cright way\u201d to grieve, no timeline for healing, and no requirement to reach a state where grief disappears completely. Instead, many people find that grief evolves over time, becoming less raw and overwhelming, and eventually becoming integrated into their ongoing life in a way that allows for both remembrance and continued living.' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Educational Component for Week 1 before continuing.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Summarize key points \u2014 do not read verbatim. Aim for 10\u201312 minutes. Accessible language only \u2014 no clinical terminology.' },
  { style: 'Normal', text: 'Facilitator Tip: If participants begin sharing personal experiences during the educational overview, validate briefly and redirect: \u201cHold that for discussion \u2014 it matters and we want to give it the right space.\u201d' },
  { style: 'Heading 2', text: 'Group Discussion & Sharing' },
  { style: 'Normal', text: '\u23f1 20\u201325 minutes' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Use the Suggested Discussion Questions above. Begin with the first and follow the group\u2019s energy. After each person shares, reflect before moving on: \u201cWhat I\u2019m hearing is\u2026 Thank you for trusting us with that.\u201d' },
  { style: 'Normal', text: '80% participant voice, 20% facilitator voice. If you are talking more than that, ask a question instead.' },
  { style: 'Normal', text: '\u2194 TRANSITION' },
  { style: 'Normal', text: 'What\u2019s alive in the room right now is exactly what this activity is designed to meet. We\u2019re not moving away from what was just shared \u2014 we\u2019re going deeper into it.' },
  { style: 'Normal', text: 'Or:  This is the first time many of you have sat in a room and spoken about your grief with others who understand. Whatever just happened in that discussion \u2014 that was real.' },
  { style: 'Normal', text: '\u2691 WATCH FOR THIS WEEK' },
  { style: 'Normal', text: '\u00b7  Someone in acute grief \u2014 within days or weeks of loss. They may have come too early. Prioritize safety and grounding over content.' },
  { style: 'Normal', text: '\u00b7  The participant who shuts down completely after the Opening Reflection. They are not disengaged \u2014 they are flooded. Create no pressure to speak.' },
  { style: 'Normal', text: '\u00b7  Anyone who arrives visibly dissociated or overwhelmed before the session begins. Check in privately before starting.' },
  { style: 'Heading 2', text: 'Grief Processing Activity' },
  { style: 'Normal', text: '\u23f1 15 minutes' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Grief Processing Activity' },
  { style: 'Normal', text: 'Grief Processing Activity: \u201cMy Grief Story\u201d' },
  { style: 'Normal', text: 'Purpose: To begin acknowledging and expressing your grief experience in a narrative form.' },
  { style: 'Normal', text: 'Materials needed: Journal or several sheets of paper, pen' },
  { style: 'Normal', text: 'Instructions:' },
  { style: 'Normal', text: 'Find a quiet, comfortable space where you won\u2019t be interrupted for at least 30 minutes.' },
  { style: 'Normal', text: 'Begin by writing about your loss. You might start with simple facts: who you lost, when it happened, and the circumstances surrounding the loss. Write as much or as little detail as feels right for you.' },
  { style: 'Normal', text: 'Next, write about your initial reactions and experiences following the loss. What were the first days and weeks like? What stands out in your memory?' },
  { style: 'Normal', text: 'Then, describe how your grief has evolved since then. Have there been changes in how you experience your grief? Have there been particularly difficult moments or periods of relative peace?' },
  { style: 'Normal', text: 'Finally, write about where you are now in your grief journey. What prompted you to begin this workbook? What are you hoping for or needing at this point?' },
  { style: 'Normal', text: 'When you\u2019ve finished writing, take a few moments to reflect on what you\u2019ve written. Notice if there were parts that were particularly difficult to write about or parts where the words flowed more easily.' },
  { style: 'Normal', text: 'Close this activity by acknowledging your courage in beginning to tell your grief story. Remember that this story will continue to evolve as you move through your grief journey.' },
  { style: 'Normal', text: 'Reflection: Your grief story is not static\u2014it will grow and change as you do. Periodically returning to this narrative throughout your journey can help you recognize how your relationship with grief evolves over time.' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Grief Processing Activity for Week 1 before continuing.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Invite participants to share one insight from their workbook \u2014 not a full entry, just one thing that stayed with them. Frame as invitation: \u201cWould anyone like to share something that came up? There is no pressure.\u201d' },
  { style: 'Normal', text: 'Facilitator Tip: Some participants will not have completed the activity at home. Normalize this entirely \u2014 they can still engage in discussion and complete it after session.' },
  { style: 'Heading 2', text: 'Living Forward Activity' },
  { style: 'Normal', text: '\u23f1 10 minutes' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Living Forward Activity' },
  { style: 'Normal', text: 'Living Forward Activity: \u201cSetting Intentions\u201d' },
  { style: 'Normal', text: 'Purpose: To establish meaningful intentions for your year of grief work and living forward.' },
  { style: 'Normal', text: 'Materials needed: Journal or paper, pen, optional: colored markers or pencils' },
  { style: 'Normal', text: 'Instructions:' },
  { style: 'Normal', text: 'Begin by considering what \u201cliving forward\u201d means to you at this point in your grief journey. This doesn\u2019t mean leaving your loved one behind or \u201cmoving on\u201d from your grief. Rather, it\u2019s about how you might carry your loved one with you as you continue to engage with life.' },
  { style: 'Normal', text: 'Reflect on what you hope might be different about your grief and your life a year from now. What qualities would you like to cultivate? What aspects of yourself would you like to nurture or develop?' },
  { style: 'Normal', text: 'Write 3-5 intentions for your year ahead. These are not goals to achieve but rather ways of being that you wish to cultivate. For example:' },
  { style: 'Normal', text: '\u201cI intend to honor my grief while also remaining open to moments of joy.\u201d' },
  { style: 'Normal', text: '\u201cI intend to care for my physical and emotional wellbeing even when grief feels overwhelming.\u201d' },
  { style: 'Normal', text: '\u201cI intend to maintain connections with supportive people in my life.\u201d' },
  { style: 'Normal', text: '\u201cI intend to find meaningful ways to remember and honor my loved one.\u201d' },
  { style: 'Normal', text: '\u201cI intend to be patient and compassionate with myself throughout this process.\u201d' },
  { style: 'Normal', text: 'For each intention, write a few sentences about why this matters to you and how you might begin to embody this intention in small ways.' },
  { style: 'Normal', text: 'If you wish, create a visual representation of your intentions\u2014perhaps a simple drawing, a collage of images, or even just writing your intentions in different colors.' },
  { style: 'Normal', text: 'Place your intentions somewhere you\u2019ll see them regularly, perhaps near where you\u2019ll be working with this book each week.' },
  { style: 'Normal', text: 'Reflection: Intentions differ from goals in that they focus on the journey rather than a destination. They provide direction without demanding specific outcomes. As you move through this workbook, you may find your intentions evolving\u2014this is a natural part of the process.' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Living Forward Activity for Week 1 before continuing.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Introduce as an invitation for the coming week, not an assignment. Describe the practice briefly, then invite: \u201cThis week, consider trying\u2026\u201d' },
  { style: 'Normal', text: 'Facilitator Tip: \u201cLiving forward doesn\u2019t mean leaving your loved one behind. It means finding how to carry them with you.\u201d Use this framing when introducing any Living Forward practice.' },
  { style: 'Heading 2', text: 'Self-Care Practice' },
  { style: 'Normal', text: '\u23f1 5 minutes' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Self-Care Practice' },
  { style: 'Normal', text: 'Self-Care Practice: \u201cComfort Corner\u201d' },
  { style: 'Normal', text: 'Purpose: To create a physical space dedicated to comfort and self-care during difficult moments.' },
  { style: 'Normal', text: 'Materials needed: Various comfort items (see suggestions below)' },
  { style: 'Normal', text: 'Instructions:' },
  { style: 'Normal', text: 'Choose a location in your home where you can create a small \u201ccomfort corner\u201d\u2014this could be a shelf, a basket, a drawer, or even a small table.' },
  { style: 'Normal', text: 'Gather items that provide comfort to your senses:' },
  { style: 'Normal', text: 'Sight: Perhaps a photo that brings positive memories, a small artwork, or an object of beauty' },
  { style: 'Normal', text: 'Sound: Maybe a small musical instrument, a recording of soothing sounds, or a bell' },
  { style: 'Normal', text: 'Smell: Consider essential oils, a scented candle, or an item that carries a comforting scent' },
  { style: 'Normal', text: 'Touch: Soft fabrics, a stress ball, a smooth stone, or something with an interesting texture' },
  { style: 'Normal', text: 'Taste: Tea bags, mints, or other non-perishable comfort foods' },
  { style: 'Normal', text: 'Add items that support emotional regulation:' },
  { style: 'Normal', text: 'A journal and pen for writing feelings' },
  { style: 'Normal', text: 'A list of supportive people you can contact' },
  { style: 'Normal', text: 'Written affirmations or comforting quotes' },
  { style: 'Normal', text: 'Instructions for simple breathing or grounding exercises' },
  { style: 'Normal', text: 'Arrange these items in your chosen space in a way that feels inviting and accessible.' },
  { style: 'Normal', text: 'Take a moment to sit with your comfort corner, noticing the items you\u2019ve gathered and how they might support you during difficult moments.' },
  { style: 'Normal', text: 'Make a simple plan for when and how you might use this space. For example: \u201cWhen I notice my grief feeling overwhelming, I\u2019ll spend 10 minutes in my comfort corner.\u201d' },
  { style: 'Normal', text: 'Reflection: Having tangible resources readily available can provide a sense of security when grief feels overwhelming. Your comfort corner is a physical reminder of your commitment to self-care and a practical tool for difficult moments.' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Self-Care Practice for Week 1 before continuing.' },
  { style: 'Heading 2', text: 'Journal Prompts' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Journal Prompts \u2014 Week 1' },
  { style: 'Normal', text: 'Take time throughout the week to reflect on one or more of these prompts:' },
  { style: 'Normal', text: 'What aspects of grief have been most surprising or unexpected for you?' },
  { style: 'Normal', text: 'In what ways has your daily life changed since your loss?' },
  { style: 'Normal', text: 'Which changes have been most challenging to adapt to?' },
  { style: 'Normal', text: 'What has provided you with comfort or support since your loss?' },
  { style: 'Normal', text: 'This might include people, activities, beliefs, or practices.' },
  { style: 'Normal', text: 'What would you like others to understand about your grief experience that might be difficult to express?' },
  { style: 'Normal', text: 'What qualities or strengths do you possess that might help you navigate this grief journey?' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Journal Prompts for Week 1 before continuing.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Journal Prompts are for independent work between sessions. Mention them briefly at close. Participants may share insights from previous journal work during the Grief Processing integration time next week.' },
  { style: 'Normal', text: '\u25b2 Trauma-Sensitive Tip: This is participants\u2019 first session. Some arrive in acute grief. Prioritize safety and belonging over content coverage. If the group is slow to open, that is appropriate \u2014 do not rush the pace.' },
  { style: 'Heading 2', text: 'Closing Affirmation & Check-Out' },
  { style: 'Normal', text: '\u23f1 5 minutes' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Weekly Affirmation' },
  { style: 'Normal', text: '\u201cI honor my grief as an expression of love. I give myself permission to feel all of my emotions. Each day, I will take one small step in caring for myself while carrying my loved one in my heart.\u201d' },
  { style: 'Normal', text: '\u25ba Invite participants to open their Participant Workbook and complete the Weekly Affirmation for Week 1 before continuing.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Read the affirmation together or invite participants to read it silently. Then check-out: each person shares one word for how they are leaving today.' },
  { style: 'Normal', text: '\u201cThank you for being here. What you each carry, you don\u2019t carry alone. Take good care of yourselves this week.\u201d' },
  { style: 'Normal', text: '\u25ce CLOSING RITUAL' },
  { style: 'Normal', text: 'You walked into something new today. Whatever you\u2019re carrying out of this room \u2014 the weight of it, the relief of being heard, the strangeness of having spoken it aloud \u2014 all of that belongs to you. Take good care of it this week.' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Gratitude Practice' },
  { style: 'Normal', text: 'Even amid grief, moments of gratitude can provide balance and perspective. Each day this week, try to identify one thing, however small, that you feel grateful for. Write these in the space below:' },
  { style: 'Normal', text: '\u25ba Point participants to the Gratitude Practice in their workbook. This is between-session work \u2014 one grateful observation per day, however small.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'Do not facilitate the Gratitude Practice in-session. Name it briefly at close: \u201cBefore next week, complete the Gratitude Practice and the Weekly Progress Tracker in your workbook. These are tools for you, not assignments to report back on.\u201d' },
  { style: 'Normal', text: '\u25ae PARTICIPANT WORKBOOK \u2014 Weekly Progress Tracker' },
  { style: 'Normal', text: 'Use this simple tracker to note your emotional state throughout the week. This can help you recognize patterns and changes over time.' },
  { style: 'Normal', text: 'Instructions: Each day, mark where you fall on each of these scales. There are no \u201cright\u201d answers\u2014this is simply a way to track your experience.' },
  { style: 'Normal', text: 'Notes: Use this space to jot down any observations, insights, or experiences that seem significant this week:' },
  { style: 'Normal', text: 'Remember: Grief is not linear, and there will be ups and downs throughout this journey. Be gentle with yourself as you begin this process, and know that taking this first step shows tremendous courage and self-compassion.' },
  { style: 'Normal', text: '\u25ba Point participants to the Weekly Progress Tracker. Remind them it is self-monitoring, not assessment \u2014 there are no right answers and nothing to report back to the group.' },
  { style: 'Normal', text: '\u25b8 FACILITATION LAYER \u2014 Facilitation Notes' },
  { style: 'Normal', text: 'The Tracker builds self-awareness across the quarter. Participants who complete it consistently will have a richer experience in Week 13. Mention this briefly at close without pressure.' },
  { style: 'Heading 2', text: 'After-Session Facilitator Notes' },
  { style: 'Normal', text: 'Complete your Facilitator Reflection Log (Appendix F) before leaving the session location or within one hour. Note any participants to follow up with, any dynamics to watch, any referrals needed.' },
  { style: 'Normal', text: 'Facilitator Tip: If anyone shared something concerning this session, check in privately before they leave. Do not wait until next session.' },
  { style: 'Normal', text: '\u2192 LOOKING AHEAD' },
  { style: 'Normal', text: 'NEXT SESSION \u2014 Week 2: The Nature of Grief. Participants will be naming what grief actually looks like for them \u2014 physically, emotionally, behaviorally, spiritually. Many arrive having never had precise language for what they\u2019ve been carrying. The opening you established this week determines how safely that naming can happen. If the group felt held today, they will return ready to go deeper.' },
];
